version: '3.8'
services:
    postgres:
        image: 'postgres:latest'
        container_name: postgres_case
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
            interval: 10s
            timeout: 5s
            retries: 1
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: dockerfile-backend
        container_name: backend
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '8080:8080'
            - '5005:5005'
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: root
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_PROFILES_ACTIVE: docker

        restart: on-failure
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile-frontend
        container_name: frontend
        ports:
            - '4200:80'
        depends_on:
            - backend
        networks:
            - app-network
volumes:
    postgres_data:
        driver: local

networks:
    app-network:
        driver: bridge
