services:
    postgres:
        image: 'postgres:latest'
        container_name: postgres_case
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend-case
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '8080:8080'
            - '5005:5005'
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: root
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_PROFILES_ACTIVE: docker

        restart: on-failure
volumes:
    postgres_data:
        driver: local
